name: flutter_shortcuts_new
description: Flutter plugin for creating static & dynamic app/conversation shortcuts on home screen.
version: 2.0.0
repository: https://github.com/krille-chan/flutter_shortcuts
issues: https://github.com/krille-chan/flutter_shortcuts/issues

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: im.fluffychat.flutter_shortcuts_new
        pluginClass: FlutterShortcutsPlugin
